#!/usr/bin/env bash

if [ $# -lt 1 ] || [ $# -gt 2 ]; then
	echo "Usage: $0 <file> [namespace=ft]"
	exit 1
fi

source fct.sh
[[ -z "$2" ]] && testedNamespace="ft" || testedNamespace="$2";

eval "$CC $CFLAGS $1 -DTESTED_NAMESPACE=${testedNamespace} -I${tested_path} && ./a.out"
